// =============================================================================
// RPC Contract - Auto-generated from Rust proc macros
// =============================================================================
// 
// DO NOT EDIT THIS FILE MANUALLY
// This file is generated by `tauri-plugin-rpc` build process
// Run `cargo build` to regenerate
//
// Generated at: 2026-01-10T00:00:00.000Z
// =============================================================================

import { createClientWithSubscriptions, type ContractRouter } from '../lib/rpc';

// =============================================================================
// Domain Types (generated from Rust structs)
// =============================================================================

export interface User {
  id: number;
  name: string;
  email: string;
  createdAt: string;
}

export interface CreateUserInput {
  name: string;
  email: string;
}

export interface UpdateUserInput {
  id: number;
  name?: string;
  email?: string;
}

export interface HealthResponse {
  status: string;
  version: string;
}

export interface SuccessResponse {
  success: boolean;
  message?: string;
}

export interface ChatMessage {
  id: string;
  userId: string;
  text: string;
  timestamp: string;
}

export interface StockPrice {
  symbol: string;
  price: number;
  change: number;
  changePercent: number;
  timestamp: string;
}

// =============================================================================
// Contract Definition (generated from Rust router)
// =============================================================================

export interface AppContract extends ContractRouter {
  health: { type: 'query'; input: void; output: HealthResponse };
  greet: { type: 'query'; input: { name: string }; output: string };
  
  user: {
    get: { type: 'query'; input: { id: number }; output: User };
    list: { type: 'query'; input: void; output: User[] };
    create: { type: 'mutation'; input: CreateUserInput; output: User };
    update: { type: 'mutation'; input: UpdateUserInput; output: User };
    delete: { type: 'mutation'; input: { id: number }; output: SuccessResponse };
  };
  
  chat: {
    messages: { type: 'subscription'; input: { roomId: string }; output: ChatMessage };
    send: { type: 'mutation'; input: { roomId: string; text: string }; output: ChatMessage };
    history: { type: 'query'; input: { roomId: string; limit?: number }; output: ChatMessage[] };
  };
  
  stocks: {
    live: { type: 'subscription'; input: { symbols: string[] }; output: StockPrice };
    quote: { type: 'query'; input: { symbol: string }; output: StockPrice };
  };
}

// =============================================================================
// Subscription Paths (generated from #[subscription] attributes)
// =============================================================================

const SUBSCRIPTION_PATHS = [
  'chat.messages',
  'stocks.live',
] as const;

// =============================================================================
// Typed Client Export
// =============================================================================

export const rpc = createClientWithSubscriptions<AppContract>({
  subscriptionPaths: [...SUBSCRIPTION_PATHS],
});
