// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a user
 */
export type CreateUserInput = { name: string, email: string, };
