// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

/**
 * Paginated response
 */
export type PaginatedResponse = { data: Array<User>, total: number, page: number, totalPages: number, };
