// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User entity
 */
export type User = { id: number, name: string, email: string, createdAt: string, };
