// Tauri RPC Plugin - TypeScript API
// Types are auto-generated by ts-rs

import { invoke } from '@tauri-apps/api/core';

// Re-export generated types
export * from './bindings';

import type {
  User,
  CreateUserInput,
  UpdateUserInput,
  PaginatedResponse,
  SuccessResponse,
  PaginationInput,
} from './bindings';

// Plugin command prefix
const PLUGIN = 'plugin:rpc|';

// Command registry - add new commands here
const commands = {
  greet: (args: { name: string }) => 
    invoke<string>(`${PLUGIN}greet`, args),
  
  getUser: (args: { id: number }) => 
    invoke<User>(`${PLUGIN}get_user`, args),
  
  listUsers: (args: { pagination?: PaginationInput } = {}) => 
    invoke<PaginatedResponse>(`${PLUGIN}list_users`, args),
  
  createUser: (args: { input: CreateUserInput }) => 
    invoke<User>(`${PLUGIN}create_user`, args),
  
  updateUser: (args: { input: UpdateUserInput }) => 
    invoke<User>(`${PLUGIN}update_user`, args),
  
  deleteUser: (args: { id: number }) => 
    invoke<SuccessResponse>(`${PLUGIN}delete_user`, args),
} as const;

// Export individual functions
export const greet = commands.greet;
export const getUser = commands.getUser;
export const listUsers = commands.listUsers;
export const createUser = commands.createUser;
export const updateUser = commands.updateUser;
export const deleteUser = commands.deleteUser;

// Export as object
export const rpc = commands;

// Type utilities
export type RpcCommands = typeof commands;
export type CommandName = keyof RpcCommands;
export type CommandInput<K extends CommandName> = Parameters<RpcCommands[K]>[0];
export type CommandOutput<K extends CommandName> = Awaited<ReturnType<RpcCommands[K]>>;
